language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# django environment
env:
  - DJANGO_VERSION=1.11.7

script:
  - python3 manage.py --noinput
